# Configuration for Predictive Maintenance System

# Dataset Settings
data:
  nasa_cmapss_url: "https://data.nasa.gov/download/ff5v-kuh6/application%2Fzip"
  local_data_dir: "data"
  train_file: "train_FD001.txt"
  test_file: "test_FD001.txt"
  rul_file: "RUL_FD001.txt"
  sequence_length: 50
  train_split: 0.8

# Feature Engineering
features:
  sensor_columns: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8", "s9", "s10", "s11", "s12", "s13", "s14", "s15", "s16", "s17", "s18", "s19", "s20", "s21"]
  operational_settings: ["os1", "os2", "os3"]
  rolling_window: 10
  normalize_method: "minmax"  # Options: minmax, zscore

# Model Parameters
models:
  random_forest:
    n_estimators: 100
    max_depth: 20
    random_state: 42
    n_jobs: -1
  
  xgboost:
    n_estimators: 100
    max_depth: 10
    learning_rate: 0.1
    random_state: 42
  
  lstm:
    units: 64
    dropout: 0.2
    epochs: 50
    batch_size: 64
    learning_rate: 0.001
    patience: 10

# Classification Thresholds
thresholds:
  healthy: 100  # RUL > 100 cycles
  warning: 50   # 50 < RUL <= 100
  critical: 50  # RUL <= 50

# Output Directories
paths:
  models_dir: "models"
  results_dir: "results"
  logs_dir: "logs"

# Random Seed
random_seed: 42